int contador = 1;
Console.WriteLine("El contador en este momento vale " +contador);
contador++;
Console.WriteLine("El contador en este momento vale " + contador);
contador++;
contador++;
contador++;
contador++;
Console.WriteLine("El contador en este momento vale " + contador);
contador--;
Console.WriteLine("El contador en este momento vale " + contador);